### ISSUE TITLE
Bad calculation of number of LEDs in fill_column_ratio

### ISSUE THREAD

**Issue by jhelwig** [jhelwig/gh-univiewer#10]
The calculation of num_leds in `fill_column_ratio` isn't quite right.

https://github.com/jhelwig/gh-univiewer/blob/0f6cff4fc82bc361b3ded5ea91f91025bbc35226/src/main.rs#L147-L154

For example, when given the values `[14, 2, 3]` we end up with 17 total LEDs instead of 16.

Since we're basically trying to do what the `map()` function in Arduino-land does, it might be worth doing something similar to [what is done there](https://github.com/arduino/Arduino/issues/2466#issuecomment-69873889).

**Comment by melissa** [comment]
How do I associate this issue with the PR I just opened?

**Comment by jhelwig** [comment]
You already did. Including the issue number in the commit message will do it. If you want to re-use an existing issue for the PR (so they have the same number), you can only do that using the `hub` client as far as I know.

**Comment by jhelwig** [comment]
Fixed by #12
